# Generated by Django 3.2.11 on 2022-01-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventario', models.TextField(blank=True, db_column='Inventario', null=True)),
                ('autor', models.TextField(blank=True, db_column='Autor', null=True)),
                ('titulo', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('edicion', models.TextField(blank=True, db_column='Edicion', null=True)),
                ('editorial', models.TextField(blank=True, db_column='Editorial', null=True)),
                ('fecha_de_edicion', models.TextField(blank=True, db_column='Fecha de Edicion', null=True)),
                ('fecha', models.TextField(blank=True, db_column='Fecha', null=True)),
                ('clasificacion', models.TextField(blank=True, db_column='Clasificacion', null=True)),
                ('precio', models.TextField(blank=True, db_column='Precio', null=True)),
                ('adquisicion', models.TextField(blank=True, db_column='Adquisicion', null=True)),
                ('proveedor', models.TextField(blank=True, db_column='Proveedor', null=True)),
                ('titulos', models.TextField(blank=True, db_column='Titulos', null=True)),
                ('volumenes', models.TextField(blank=True, db_column='Volumenes', null=True)),
                ('baja', models.TextField(blank=True, db_column='Baja', null=True)),
                ('pais', models.TextField(blank=True, db_column='Pais', null=True)),
                ('ejemplares', models.TextField(blank=True, db_column='Ejemplares', null=True)),
                ('tipo_documento', models.TextField(blank=True, db_column='Tipo Documento', null=True)),
                ('comentario', models.TextField(blank=True, db_column='Comentario', null=True)),
            ],
            options={
                'db_table': 'Catalogo',
                'managed': False,
            },
        ),
    ]
